//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int id_deal { get; set; }
        public Nullable<int> id_offers { get; set; }
        public Nullable<int> id_requirement { get; set; }
    
        public virtual Offers Offers { get; set; }
        public virtual Requirement Requirement { get; set; }
    }
}
