//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RealEstate()
        {
            this.Offers = new HashSet<Offers>();
        }
    
        public int id_object { get; set; }
        public string object_type { get; set; }
        public Nullable<int> rooms { get; set; }
        public Nullable<double> square { get; set; }
        public Nullable<int> floor { get; set; }
        public Nullable<int> number_of_floors { get; set; }
        public string address_city { get; set; }
        public string address_street { get; set; }
        public Nullable<int> address_house { get; set; }
        public Nullable<int> address_number { get; set; }
        public Nullable<int> coordinate_latitude { get; set; }
        public Nullable<int> coordinate_longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offers> Offers { get; set; }
    }
}
