//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requirement()
        {
            this.Deal = new HashSet<Deal>();
        }
    
        public int id_requirement { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<int> id_realtor { get; set; }
        public string object_type { get; set; }
        public string address_city { get; set; }
        public string address_street { get; set; }
        public Nullable<int> address_house { get; set; }
        public Nullable<int> address_namber { get; set; }
        public Nullable<int> max_price { get; set; }
        public Nullable<int> min_price { get; set; }
        public Nullable<int> max_square { get; set; }
        public Nullable<int> min_square { get; set; }
        public Nullable<int> max_number_of_rooms { get; set; }
        public Nullable<int> min_number_of_rooms { get; set; }
        public Nullable<int> max_floor { get; set; }
        public Nullable<int> min_floor { get; set; }
        public Nullable<int> max_number_of_floors { get; set; }
        public Nullable<int> min_number_of_floors { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deal { get; set; }
        public virtual Realtors Realtors { get; set; }
    }
}
